[project]
authors = ["ElPhysico <vkkleinqt@gmail.com>"]
channels = ["conda-forge"]
name = "options-market-maker"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
numpy = "*"
scipy = "*"
pandas = "*"
matplotlib = "*"
pytest = "*"
jupyter = "*"